<? html::block('head', html::css('~/tag/quote/style.css')); ?>

<? if ($attr['cite']){ ?>
    <blockquote class="<?=$attr['class']; ?>" cite="<?=$attr['cite']['href']; ?>">
        <?=$attr['#text']; ?>

        <div align="right">
            <a href="<?=$attr['cite']['href']; ?>"><?=$attr['cite']['text']; ?></a>
        </div>
    </blockquote>
<? } else { ?>
    <blockquote class="<?=$attr['class']; ?>"><?=$attr['#text']; ?></blockquote>
<? } ?>