<h1>Home</h1>

<p>
    Это главная страница, грузится по умолчанию. Можно изменить в data/config/lib.b.yaml директивы show (для шаблона) и load (для модуля).<br />
    Модуль лежит тут load/home/index.php.<br />
    Шаблон - тут show/home/index.phtml.
</p>

<p><a href="http://goodgirl.ru/berry/docs/">Документация</a>.</p>

<h2>Пользовательские теги</h2>

<p>
    Тег &lt;hello_world />:<br />
    <hello_world />
</p>

<p>
    Тег &lt;typo:ru>&lt;hello_world />&lt;/typo:ru>:<br />
    <typo:ru><hello_world /></typo:ru>
</p>

<h2>Аттрибут check и проверка формы</h2>

<form method="post">
    <p>Тут должно быть число от 0 до 15:</p>

    <p>
        <input name="test[int]" type="text" check:re="int(0, 15)" check:need="Введите число от 0 до 15." />
    </p>

    <p>А тут дата в формате ГГГГ-ММ-ДД:</p>

    <p>
        <input name="test[date]" type="text" check:re="date" check:need="Введите дату в формате ГГГГ-ММ-ДД." />
    </p>

    <p>Ну, и картинку с расширением GIF либо оставить поле пустым:</p>

    <p>
        <input name="test[file]" type="file" check:re="ext(gif) or empty" check:need="Нужно указать картинку с расширением GIF или оставить поле пустым." />
    </p>

    <p>
        <input type="submit" value="Отправить" />
    </p>
</form>