<h1>Home</h1>

<p>
    Это главная страница, грузится по умолчанию. Можно изменить в <dfn>lib/berry/b.yml</dfn> директивы <dfn>show</dfn> (для шаблона) и <dfn>load</dfn> (для модуля) указывающие на то, что должно подгружаться по умолчанию. Сейчас это <dfn>index</dfn> (на выходе <dfn>mod/index.phtml</dfn>) и <dfn>home</dfn> (на выходе <dfn>mod/home/index.php</dfn>), соответственно.
</p>

<h2>Ссылки</h2>

<p>
    <li><a href="http://goodgirl.ru/berry/docs/">Документация</a></li>
    <li><a href="http://forum.goodgirl.ru/">Форум</a></li>
    <li><a href="http://svn.goodgirl.ru/berry/">Subversion</a></li>
</p>

<h2>Пользовательские теги</h2>

<p>
    Тег <dfn class="tag">&lt;hello_world /></dfn>:<br />
    <hello_world /><br />
</p>

<p>
    Тег <dfn class="tag">&lt;typo:ru>&lt;hello_world />&lt;/typo:ru></dfn>:<br />
    <typo:ru><hello_world /></typo:ru>
</p>

<h2>Аттрибут check и проверка формы</h2>

<div id="ajax[test]">
    <!--
        Пихаем ошибку от обычно посланной формы в блок ответа аякса,
        чтобы не плодить ошибки в случае, если послать и так, и сяк.
    -->

    ${error}
</div>

<form method="post" enctype="multipart/form-data">
    <p>Тут должно быть число от 0 до 15:</p>

    <p>
        <input name="test[int]" type="text" check:re="int(0, 15)" check:need="Введите число от 0 до 15." />

        <? if (${errors}){ ?>
            <span style="color: #c60000">&lt;- тут ошибка: ${errors.test\.int.1}</span>
        <? } ?>
    </p>

    <p>Тут дата в формате ГГГГ-ММ-ДД:</p>

    <p>
        <input name="test[date]" type="text" check:re="date" check:need="Введите дату в формате ГГГГ-ММ-ДД." />
        <js:calendar for="test[date]" format="%Y-%m-%d" />
    </p>

    <p>Тут используем своё регулярное выражение для проверки:</p>

    <p>
        <input name="test[hello]" type="text" check:re="/^h(el|a)lo$/i" check:need="Введите "hello" или  "halo"." />
    </p>

    <p>Ну, и картинку с расширением GIF либо оставить поле пустым:</p>

    <p>
        <input name="test[file]" type="file" check:re="ext(gif) or empty" check:need="Нужно указать картинку с расширением GIF или оставить поле пустым." />
    </p>

    <p>
        <input type="submit" value="Отправить (стандартно)" />
        <input type="button" value="Отправить (аякс)" ajax:call="/home/ajax" ajax:id="test" />
    </p>
</form>