<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
	<head>
		<title>${config.site.name}</title>

        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <base href="${q.0}/" />

        <link href="~/asset/style.css" rel="stylesheet" type="text/css" media="screen" />

        <!-- <script type="text/javascript" src="~/asset/js/prototype.js"></script>
        <script type="text/javascript" src="~/asset/js/berry.js"></script>

        <script type="text/javascript" src="~/asset/js/JsHttpRequest/JsHttpRequest.js"></script>
        <script type="text/javascript" src="~/asset/js/JsHttpRequest/JsHttpRequest-prototype.js"></script>

        <script type="text/javascript" src="~/asset/js/jquery.pack.js"></script>
        <script type="text/javascript">
            var $J = jQuery.noConflict();
        </script>

        <style>
            #tooltip {
                background: #fff;
                border: 1px solid #000;
                color: #000;
                font-family: verdana, arial, helvetica, sans-serif;
            	font-size: 11px;
            	margin: 15px;
            	padding: 2px;
            }
        </style> -->

		<block:head />
    </head>

    <body>
        <msg id="i" />
        <msg id="e" />
        <block:body />

        <block:foot />
    </body>
</html>