<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
    <head>
        <show src="temp.head" />
        <title>Публичный доступ временно закрыт</title>
        <link href="~/asset/css/lite.css" rel="stylesheet" type="text/css" media="screen" />
        <block:head />
    </head>

    <body>

        <div>
            Публичный доступ к сайту временно закрыт.
            <span if="!$b{config.site.name}">У нас какие-то проблемы с базой данных.</span>
            Зайдите, пожалуйста, позже.
        </div>

        <block:foot />
    </body>
</html>