<?=(${prev} ? '<a href="'.$prev.'">←</a>' : '←'); ?>

<? if ($array = $pages[0]){ ?>
    <? foreach ($array as $page => $href){ ?>
        <?=(${page} == $current ? '<b>['.$page.']</b>' : '<a href="'.$href.'">['.$page.']</a>'); ?>
    <? } ?>

    ...
<? } ?>

<? if ($array = $pages[1]){ ?>
    <? foreach ($array as $page => $href){ ?>
        <?=(${page} == $current ? '<b>['.$page.']</b>' : '<a href="'.$href.'">['.$page.']</a>'); ?>
    <? } ?>
<? } ?>

<? if ($array = $pages[2]){ ?>
    ...

    <? foreach ($array as $page => $href){ ?>
        <?=(${page} == $current ? '<b>['.$page.']</b>' : '<a href="'.$href.'">['.$page.']</a>'); ?>
    <? } ?>
<? } ?>

<?=(${next} ? '<a href="'.$next.'">→</a>' : '→'); ?>