<table class="tab" cellpadding="0" cellspacing="0">
    <tr>
        <loop each="i, tab in %{tabs}">
            <td class="menu on" id="tag_tabs[menu_%{i}]" if="%{tab.open}">
                <nobr>
                    <a href="#" onclick="
                        %{tab.click};
                        $('tag_tabs[tab_%{i}]').show();
                        $('tag_tabs[menu_%{i}]').removeClassName('off').addClassName('on');
                        return false;
                    ">%{tab.title}</a>
                </nobr>
            </td>

            <td class="menu off" id="tag_tabs[menu_%{i}]" if="!%{tab.open}">
                <nobr>
                    <a href="#" onclick="
                        %{tab.click};
                        $('tag_tabs[tab_%{i}]').show();
                        $('tag_tabs[menu_%{i}]').removeClassName('off').addClassName('on');
                        return false;
                    ">%{tab.title}</a>
                </nobr>
            </td>
        </loop>

        <td width="99%" class="none"><img src="~/asset/img/1x1.gif" width="1" height="1" alt="" /></td>
    </tr>
</table>

<loop each="i, tab in %{tabs}">
    <table cellpadding="0" cellspacing="0" id="tag_tabs[tab_%{i}]" class="tab" if="%{tab.open}">
        <tr>
            <td class="content">%{tab.#text}</td>
        </tr>
    </table>

    <table cellpadding="0" cellspacing="0" id="tag_tabs[tab_%{i}]" style="display: none;" class="tab" if="!%{tab.open}">
        <tr>
            <td class="content">%{tab.#text}</td>
        </tr>
    </table>
</loop>