<?=(${prev} ? '<a href="'.$prev.'">←</a>' : '←'); ?>

<? foreach ($pages as $page => $href){ ?>
    <? if ($page == $current){ ?>
        <b>[<?=($page * $attr['limit'] - $attr['limit'] + 1).'-'.($page * $attr['limit']); ?>]</b>
    <? } else { ?>
        <a href="${href}">[<?=($page * $attr['limit'] - $attr['limit'] + 1).'-'.($page * $attr['limit']); ?>]</a>
    <? } ?>
<? } ?>

<?=(${next} ? '<a href="'.$next.'">→</a>' : '→'); ?>