<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
	<head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>index.phtml</title>

        <link type="text/css" rel="stylesheet" href="~/asset/style.css" media="screen" />
        <script type="text/javascript" src="~/lib/JsHttpRequest/JsHttpRequest.js"></script>

		<block:head />
    </head>

    <body>
        <div class="head">
            <a href="http://goodgirl.ru/"><img src="~/asset/goodgirl.png" alt="GoodGirl inc." /></a><a href="http://goodgirl.ru/berry/"><img src="~/asset/logo.jpg" alt="Berry" /></a>
        </div>

        <msg id="i" />
        <msg id="e" />

        <block:body />

        <block:foot />
    </body>
</html>